src/blog/urls.py
from django.urls import path

from blog.views import BlogPostDetail, BlogHome, PostDelete

app_name = 'blog'

urlpatterns = [
    path('', BlogHome.as_view(), name="home"),
    path('<str:slug>/', BlogPostDetail.as_view(), name='post'),
    path('<str:slug>/delete', PostDelete.as_view(), name='delete'),

]

src/gallery/urls.py
from django.urls import path

from gallery.views import GalleryDelete, GalleryHome, GalleryDetail

app_name = 'gallery'


urlpatterns = [
    path('', GalleryHome.as_view(), name="home"),
    path('<str:slug>/', GalleryDetail.as_view(), name='detail'),
    path('<str:slug>/delete', GalleryDelete.as_view(), name='delete'),

]

src/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from website.views import  home

urlpatterns = [
    path('admin_nadsun/', admin.site.urls, ),
    path('', home, name="home"),
    path('blog/', include('blog.urls')),
    path('gallery/', include('gallery.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('sendemail.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/gallery/models.py
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

from PIL import Image
from _utils import resize_img, has_changed
import os



User = get_user_model()

class Gallery(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    created_on = models.DateTimeField(default=timezone.now, null=True, verbose_name="Date de publication")
    published = models.BooleanField(default=False, verbose_name="Publié")
    content = models.CharField(max_length=255, blank=True, verbose_name="Contenu")
    image = models.ImageField(upload_to='gallery')
    alt = models.CharField(default=False, max_length=255, verbose_name="Texte alternatif")

    class Meta:
        ordering = ['-created_on']
        verbose_name = "Image"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if has_changed(self, "image"):
            
            filename = os.path.splitext(self.image.name)[0]
            filename = f"{filename}.jpg"
            
            img = Image.open(self.image.file)
            
            if img.mode not in ('L', 'RGB'):
                img = img.convert('RGB')
            
            self.image.save(filename, resize_img(img, (1000,1000)), save=False)
            
        
        
        if not self.slug:
           self.slug = slugify(self.title)

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('home')




   

src/gallery/views.py
import os
from django.urls import reverse_lazy

from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from gallery.models import Gallery


class GalleryHome(ListView):
    model = Gallery
    template_name = 'gallery/index.html'
    context_object_name = "images"


    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        return queryset.filter(published=True)


class GalleryDetail(DetailView):
    model = Gallery
    template_name = "gallery/detail.html"
    context_object_name = "image"


    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        return queryset.filter(published=True)


    def get_first(self):
        first_object = self.get_queryset().latest('created_on')
        return first_object if first_object else None

    def get_last(self):
        last_object = self.get_queryset().earliest('created_on')
        return last_object if last_object else None

    def get_next(self, current_object_date):
        next_object = self.get_queryset().order_by('-created_on').filter(created_on__lt=current_object_date).first()
        return next_object if next_object else None

    def get_previous(self, current_object_date):
        previous_object = self.get_queryset().order_by('created_on').filter(created_on__gt=current_object_date).first()
        return previous_object if previous_object else None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_object_date = self.object.created_on
        context['next_image'] = self.get_next(current_object_date)
        context['last_image'] = self.get_last()
        context['first_image'] = self.get_first()
        context['previous_image'] = self.get_previous(current_object_date)
        return context


@method_decorator(login_required, name='dispatch')
class GalleryDelete(DeleteView):
    model = Gallery
    template_name = 'website/delete.html'
    success_url = reverse_lazy("gallery:home")
    context_object_name = "image"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Supprimer l'image"
        context['object'] = self.get_object().title
        context['url'] = self.success_url
        context['url_title'] = "Retour vers la galerie"
        return context
    
    def form_valid(self,form):
                
        image = self.get_object()
        
        os.remove(str(image.image.path))
                
        return super().form_valid(form)
    
    

src/gallery/templates/gallery/detail.html
{% extends 'base.html' %}


{% block title %} <title>{{ image.title }}</title> {% endblock %}

{% block content %}

    <main id="gallery-detail">

        <div class="image-container">
            {% if request.user.is_authenticated %}
            {% include "website/tools.html" %}
            {% endif %}
            <h1>{{ image.title }}</h1>
            <img src="{{ image.image.url }}" alt="{{ image.alt}}">
            <div class="content">
                <p class="legend">{{ image.content|safe }}</p>
            </div>
        </div>

        <ul class="item-nav">

            {% if previous_image %}
                <li><a href="{% url 'gallery:detail' slug=first_image.slug %}">Début</a>
            {% else %}
                <li disabled>Début</button>
            {% endif %}
                </li>

            {% if previous_image %}
                <li><a href="{% url 'gallery:detail' slug=previous_image.slug %}">&laquo; Précédente</a>
            {% else %}
                <li disabled>&laquo; Précédente</button>
            {% endif %}
            </li>

            <li><a href="{% url 'gallery:home' %}">Retour à la gallerie</a></li>

            {% if next_image %}
                <li><a href="{% url 'gallery:detail' slug=next_image.slug %}">Suivante &raquo</a>
            {% else %}
                <li disabled>Suivante &raquo;</button>
            {% endif %}
            </li>

            {% if next_image %}
                <li><a href="{% url 'gallery:detail' slug=last_image.slug %}">Dernière</a>
            {% else %}
                <li disabled>Dernière</button>
            {% endif %}
            </li>

        </ul>
    </main>

{% endblock %}

src/gallery/templates/gallery/index.html
{% extends 'base.html' %}


{% block title %} <title>Du soleil dans ma palette : la gallerie</title> {% endblock %}

{% block content %}
    <main id="gallery">
        <h1>La galerie du soleil dans ma palette</h1>
        <div class="grid">
            {% for image in images %}
            <div class="image-item">
                {% if request.user.is_authenticated %}
                {% include "website/tools.html" %}
                {% endif %}
                <img src="{{ image.image.url }}" alt="{{ image.alt }}">
                <div class="legend">
                    <a href="{% url 'gallery:detail' slug=image.slug %}"><h3>{{ image.title }}</h3></a>
                    <p>{{ image.content|safe|truncatewords:06 }}</p>

                </div>

            </div>
             {% endfor %}
     </div>
    </main>

{% endblock %}