src/blog/urls.py
from django.urls import path

from blog.views import BlogPostDetail, BlogHome, PostDelete

app_name = 'blog'

urlpatterns = [
    path('', BlogHome.as_view(), name="home"),
    path('<str:slug>/', BlogPostDetail.as_view(), name='post'),
    path('<str:slug>/delete', PostDelete.as_view(), name='delete'),

]

src/gallery/urls.py
from django.urls import path

from gallery.views import GalleryDelete, GalleryHome, GalleryDetail

app_name = 'gallery'


urlpatterns = [
    path('', GalleryHome.as_view(), name="home"),
    path('<str:slug>/', GalleryDetail.as_view(), name='detail'),
    path('<str:slug>/delete', GalleryDelete.as_view(), name='delete'),

]

src/sendemail/urls.py
from django.urls import path

from sendemail.views import SuccessView, ContactView

app_name = "sendemail"

urlpatterns = [
    path("contact/", ContactView.as_view(), name="contact"),
    path("success/", SuccessView.as_view(), name="success"),
]

src/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from website.views import  home

urlpatterns = [
    path('admin_nadsun/', admin.site.urls, ),
    path('', home, name="home"),
    path('blog/', include('blog.urls')),
    path('gallery/', include('gallery.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('sendemail.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock %}
    <!-- <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" > -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.min.css'%}" />
    <link rel="shortcut icon" href="{% static 'favicon/sun.svg' %}"/>
</head>
<body>
    <header id="acceuil">

        {% block header %}{% endblock %}

        <nav class="main-nav">
            <div class="hamburger-btn">
                <div class="ligneUnique"></div>
            </div>
            <ul>
                <li><a href="{% url 'home' %}">Acceuil</a></li>
                <li><a href="{% url 'blog:home' %}">Journal d'Atelier</a></li>
                <li><a href="{% url 'gallery:home' %}">Galerie</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'admin:index' %}">Administration</a></li>
                {% endif %}

            </ul>
        </nav>
     </header>

    {% block content %}{% endblock %}



    <footer>
        <div class="social-container">

            <a href="https://www.facebook.com/naddessine" class="icon">
                <i class="fab fa-facebook-f"></i>
            </a>
            <a href="https://www.instagram.com/nad_dessine/" class="icon">

                <i class="fab fa-instagram"></i>
            </a>
            <a href="{% url 'sendemail:contact' %}" class="icon">

                <i class="fa-solid fa-envelope"></i>
            </a>

        </div>
        <p>Made with <a href="{% url 'admin:login' %}">&#9825;</a> by NAD &copy; | 2024 </p>
    </footer>
    <script src="{% static 'scripts/script_navigation.js' %}"></script>
    {% block script %}{% endblock script %}
</body>
</html>