src/blog/urls.py
from django.urls import path

from blog.views import BlogPostDetail, BlogHome, PostDelete

app_name = 'blog'

urlpatterns = [
    path('', BlogHome.as_view(), name="home"),
    path('<str:slug>/', BlogPostDetail.as_view(), name='post'),
    path('<str:slug>/delete', PostDelete.as_view(), name='delete'),

]

src/gallery/urls.py
from django.urls import path

from gallery.views import GalleryDelete, GalleryHome, GalleryDetail

app_name = 'gallery'


urlpatterns = [
    path('', GalleryHome.as_view(), name="home"),
    path('<str:slug>/', GalleryDetail.as_view(), name='detail'),
    path('<str:slug>/delete', GalleryDelete.as_view(), name='delete'),

]

src/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from website.views import  home

urlpatterns = [
    path('admin_nadsun/', admin.site.urls, ),
    path('', home, name="home"),
    path('blog/', include('blog.urls')),
    path('gallery/', include('gallery.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('sendemail.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/website/views.py
from django.shortcuts import render

from blog.models import BlogPost
from gallery.models import Gallery
from reel.models import Reels


def home(request):
    posts = BlogPost.objects.all().order_by("-created_on").filter(published=True)[:3]
    images = Gallery.objects.all().order_by("-created_on").filter(published=True)[:5]
    reels = Reels.objects.all().order_by("-created_on").filter(published=True)[:4]
    return render(request, "website/index.html", context={"posts": posts, "images": images, "reels":reels})

src/website/templates/website/delete.html
{% extends 'base.html' %}

{% block title %}<title>{{ title }}</title>{% endblock %}

{% block content %}

    <main id="delete">

        <a href="{{ url }}">{{ url_title }}</a>
    
        <form method="POST">
            {% csrf_token %}
            <p>Voulez-vous supprimer "{{ object }}"</p>
            
            <input type="submit" value="Supprimer">
    
        </form>
    </main>
    

{% endblock %}

src/website/templates/website/tools.html
{% if post %}

    <div class="tools">
        <a href="{% url 'admin:blog_blogpost_add' %}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM232 344l0-64-64 0c-13.3 0-24-10.7-24-24s10.7-24 24-24l64 0 0-64c0-13.3 10.7-24 24-24s24 10.7 24 24l0 64 64 0c13.3 0 24 10.7 24 24s-10.7 24-24 24l-64 0 0 64c0 13.3-10.7 24-24 24s-24-10.7-24-24z"/></svg>
        </a>
        <a href="{% url 'admin:blog_blogpost_change' post.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M373.5 27.1C388.5 9.9 410.2 0 433 0c43.6 0 79 35.4 79 79c0 22.8-9.9 44.6-27.1 59.6L277.7 319l-10.3-10.3-64-64L193 234.3 373.5 27.1zM170.3 256.9l10.4 10.4 64 64 10.4 10.4-19.2 83.4c-3.9 17.1-16.9 30.7-33.8 35.4L24.3 510.3l95.4-95.4c2.6 .7 5.4 1.1 8.3 1.1c17.7 0 32-14.3 32-32s-14.3-32-32-32s-32 14.3-32 32c0 2.9 .4 5.6 1.1 8.3L1.7 487.6 51.5 310c4.7-16.9 18.3-29.9 35.4-33.8l83.4-19.2z"/></svg>
        </a>
        <a href="{% url 'blog:delete' slug=post.slug %}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M135.2 17.7L128 32 32 32C14.3 32 0 46.3 0 64S14.3 96 32 96l384 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-96 0-7.2-14.3C307.4 6.8 296.3 0 284.2 0L163.8 0c-12.1 0-23.2 6.8-28.6 17.7zM416 128L32 128 53.2 467c1.6 25.3 22.6 45 47.9 45l245.8 0c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg>
        </a>
    </div>

{% else %}
    <div class="tools">
        <a href="{% url 'admin:gallery_gallery_add' %}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM232 344l0-64-64 0c-13.3 0-24-10.7-24-24s10.7-24 24-24l64 0 0-64c0-13.3 10.7-24 24-24s24 10.7 24 24l0 64 64 0c13.3 0 24 10.7 24 24s-10.7 24-24 24l-64 0 0 64c0 13.3-10.7 24-24 24s-24-10.7-24-24z"/></svg>
        </a>
        <a href="{% url 'admin:gallery_gallery_change' image.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M373.5 27.1C388.5 9.9 410.2 0 433 0c43.6 0 79 35.4 79 79c0 22.8-9.9 44.6-27.1 59.6L277.7 319l-10.3-10.3-64-64L193 234.3 373.5 27.1zM170.3 256.9l10.4 10.4 64 64 10.4 10.4-19.2 83.4c-3.9 17.1-16.9 30.7-33.8 35.4L24.3 510.3l95.4-95.4c2.6 .7 5.4 1.1 8.3 1.1c17.7 0 32-14.3 32-32s-14.3-32-32-32s-32 14.3-32 32c0 2.9 .4 5.6 1.1 8.3L1.7 487.6 51.5 310c4.7-16.9 18.3-29.9 35.4-33.8l83.4-19.2z"/></svg>
        </a>
        <a href="{% url 'gallery:delete' slug=image.slug %}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M135.2 17.7L128 32 32 32C14.3 32 0 46.3 0 64S14.3 96 32 96l384 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-96 0-7.2-14.3C307.4 6.8 296.3 0 284.2 0L163.8 0c-12.1 0-23.2 6.8-28.6 17.7zM416 128L32 128 53.2 467c1.6 25.3 22.6 45 47.9 45l245.8 0c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg>
        </a>
    </div>
  
{% endif %}